# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Sketches Of Tonita"
description:	       "Tonita is 'Fraponic' for 'woman who is like an uncle'. This person illustrates the society after the collapse of the French and Japanese empires in North America. The culture can be described as a mixture of Alsatian and Japanese. The art style is influenced by Hakusai and Oncle Hanzi."

author:              "S.R. Weaver"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
